language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t wngusrud27/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true wngusrud27/react-test-app npm run test

after_success:
  - docker build -t wngusrud27/docker-frontend ./frontend
  - docker build -t wngusrud27/docker-backend ./backend
  - docker build -t wngusrud27/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push wngusrud27/docker-frontend 
  - docker push wngusrud27/docker-backend 
  - docker push wngusrud27/docker-nginx 

deploy:
  provider: elsaticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: Dockerfullstackapp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-895948757088 #생성이 안되어 기존에 있던 것을 이용하는 것으로 추측됨
  bucket_path: "docker-fullstack-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key_id: $AWS_SECRET_ACCESS_KEY
